### ISSUE TITLE
FedRAMP Tailored Comments - ServiceNow

### ISSUE THREAD

**Issue by mhettinger25** [GSA/fedramp-tailored#132] opened 2017-04-19 19:35 UTC
FedRAMP Tailored Comments - Submitted by ServiceNow, Inc.

ServiceNow thanks you for the opportunity to provide comments to the FedRAMP Program Office regarding the proposed FedRAMP Tailored initiative.  We support the PMO’s efforts to update the FedRAMP program aimed at streamlining the certification process for certain software as a service offerings, while maintaining the highest levels of security for federal information in commercial clouds.  
ServiceNow believes that FedRAMP Tailored directly supports the recent Executive Order from President Trump dated 12 April 2017 (Comprehensive Plan for Reforming the Federal Government and Reducing the Federal Civilian Workforce).  A few examples where the 12 April 2017 President’s Executive Order can leverage FedRAMP Tailored to have an immediate impact are:

•	Replacing expensive outdated legacy IT systems
•	Providing a technology that will make the workforce more effective and efficient
•	Automate and improve customer service internally and externally
•	Allow the federal government the ability to understand the cost of doing business
•	Streamline how policy is created, changed and measured
•	Provide the capability to rapidly identify and where applicable merge or replace duplicate applications, and sundown unused/legacy applications
•	Mobilize and consumerize their workforce

General Comments:
FedRAMP’s “approve once, use many times” philosophy is critical as the federal government looks to promote agency transition to cloud computing, but the program must evolve to ensure effective adoption by government agencies.  We encourage the FedRAMP PMO to continue to push improvements that make the overall program better, faster and more cost effective for participants, recognizing that as new technologies come to market the program must be flexible enough to accommodate new and innovative technologies, without becoming cost prohibitive.  Furthermore, we encourage the PMO to work with agencies to better leverage those companies that have achieved FedRAMP certification by requiring FedRAMP certification when acquiring cloud services to the maximum extent practicable.  It is by leveraging FedRAMP approved vendors that agencies will begin to realize the full efficiencies and security benefits that come from state-of-the-art cloud technologies. 

Low Impact SaaS
The changes proposed as part of FedRAMP Tailored, namely providing a new lower baseline that contains a minimum set of security control requirements for low-impact software-as-a-service (LISaaS) in an existing FedRAMP approved environment (essentially as a “plug-in” or “ride-along”) makes sense as not every federal software-as-a-service (SaaS) offering touches classified, sensitive or personally identifiable information.  We believe as the PMO stated in its announcement that this gives the government authorizing officials a standardized approach to determining the risks associated with authorizing specific low-impact cloud applications that do not directly impact the government’s mission needs.

Clear Guidance is needed on When FedRAMP Tailored Applies
Critical for the PMO going forward is applying the criteria for FedRAMP Tailored in a way that does not adversely impact cloud security or unfairly disadvantage any company that either currently holds a FedRAMP SaaS certification or is in process at the higher security levels (low, moderate, high).  As you know, over 100 federal government cloud service providers have invested millions of dollars to achieve FedRAMP approval and more than 30 of those have offered and had approved SaaS offerings.  It is critical that those investments are protected, while also providing a new avenue for software as a service and related applications to achieve FedRAMP Tailored certification when that is the appropriate path.  To that end, we encourage the PMO following the completion of the open comment period on FedRAMP Tailored to issue clear guidelines to the agencies and federal IT community establishing when FedRAMP is required, when FedRAMP Tailored is sufficient and if there are circumstances where agencies should consider leveraging cloud services without any FedRAMP certification at all.

According to the proposal, FedRAMP Tailored is the appropriate path for a cloud offering if the following criteria are met.  

1.	Must operate in an existing FedRAMP certified IaaS or PaaS environment
2.	Must currently be operational itself
3.	Must be software-as-a-service (SaaS)
4.	Does not require the collective of PII
5.	Is defined as low impact according to FIPS 199

Clarifying “Inheritance” and any SaaS offering in a FedRAMP environment
By highlighting the 112 controls that make up the FedRAMP Tailored baseline one can assume that in meeting this lower bar the SaaS provider is also inheriting the existing controls from the approved IaaS or PaaS offering on which it resides.  Inheritance is a point of emphasis in the overall FedRAMP process that we believe should be clarified particularly in light of the new FedRAMP Tailored guidelines.  
As part of that review we encourage you to address the issue of SaaS application plug-ins that may touch sensitive, classified or PII in a similar manner to what you are trying to address with FedRAMP Tailored i.e. finding a way to expedite any SaaS offering that is proposed for FedRAMP certification that operates in a FedRAMP certified infrastructure-as-a-service (IaaS) or platform-as-a-service (PaaS) environment.

Thank you and please let us know if you have any questions.

**Comment by FedRAMP** [comment] 2017-07-11 12:17
Thank you for your comment. This appears to be a duplicate of comment #138. Please see that comment for disposition.

**Comment by cbukovac** [comment] 2017-07-13 17:09
Closed in preparation for V2 release

**Closed as completed by cbukovac** 2017-07-13 17:09 UTC
Labels: Public Comments
